version: '3'

services:
  gdb:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: treollapi
      MYSQL_TCP_PORT: 3306
    restart: on-failure

  gapi:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - gdb

  gui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - gapi
